### ISSUE TITLE
Submariner 2.10 installation fails on VMWare with OCP 4.15

### ISSUE THREAD

**Issue by vthapar** [stolostron/submariner-addon#1372]
SubmarinerAddon installation on VMWare running OCP 4.15+ fails. Only submariner-addon pod is created. Addon pod shows error as such:

```
E0321 00:58:14.099083 1 base_controller.go:266] "SubmarinerAgentController" controller failed to sync "perf2", err: failed to create submariner brokerInfo of cluster perf2 : secrets "perf2" not found
```

This is because 4.15+ onwards OCP doesn't create the secret automatically for the SA. Submariner requires this secret to extract broker credentials to configure submariner on managed clusters.

Fix is for addon to create the `Secret` of type `ServiceAccount` if not already present.

Workaround
-------------------
Example workaround steps for Managed cluster `perf2` that is part of clusterset `submariner`

1. Go to Hub cluster.

2. oc apply the following template

 

```
apiVersion: v1
kind: Secret
metadata:
  name: perf2-dockercfg
  namespace: submariner-broker
  annotations:
    kubernetes.io/service-account.name: perf2
    openshift.io/token-secret.name: perf2-dockercfg
    openshift.io/token-secret.value: perf2-dockercfg
type: kubernetes.io/service-account-token
```
 

3. Get the token from the created secret

```
% oc get secrets -n submariner-broker perf2-dockercfg -o yaml 
data:
  token: <token1>
```
4. Decode the data.token to get the real token

`echo <token1 copied from data.token> |base64 -d `
5. Update the token to the created secret annotation

```
% oc edit secrets -n submariner-broker perf2-dockercfg
metadata:
  annotations:
    openshift.io/token-secret.value: <paste the decoded token>
```
6. Link the modified secret to the SA

```
% oc edit sa -n submariner-broker perf2
....
secrets:
- name: perf2-dockercfg
```
7. Check that ManifestWork `submariner-resource` is created in `perf2` namespace. This can take a while as Addon keeps retrying with an exponential backoff. If taking too long, can restart hub addon pod, but recommended to do so only after secrets have been created and linked for all managedclusters.
