### ISSUE TITLE
The wrong info in submariner-addon/docs/submarinerConfig.md

### ISSUE THREAD

**Issue by mheppler-rh** [stolostron/submariner-addon#2126]
There is a bug in docs/submarinerConfig.md. The point 5 is non-sense:

- the description is the same like in the point 6, even with typo.
- the code snippet was probably copied from the point 4 and updated. But the key `spec.gatewayConfig` is wrong in this context. The probably correct code may look:

```
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: <config-name>
    namespace: <managed-cluster-namespace>
spec:
    SubscriptionConfig:
       source: <submariner-operator-source>
       sourceNamespace: <submariner-operator-source-namespace>
       channel: <submariner-operator-channel>
       startingCSV: <submariner-operator-staring-csv>
    ...
```

This bug is in all actual branches.
