### ISSUE TITLE
[2.6] Unable to use custom submariner images

### ISSUE THREAD

**Issue by vthapar** [stolostron/submariner-addon#452]
When using OCP 4.10+ACM 2.6, even when modifying submarinerconfig to use a different submariner image, it doesn't apply correclty. Changes get applied to `submariner` in operator namespace but deployments/daemonsets continue to use old image.

**SubmarinerConfigs**
 ```
   imagePullSpecs:
      lighthouseAgentImagePullSpec: quay.io/submariner/lighthouse-agent:0.13.0
      lighthouseCoreDNSImagePullSpec: quay.io/submariner/lighthouse-coredns:0.13.0
      submarinerGlobalnetImagePullSpec: quay.io/submariner/submariner-globalnet:0.13.0
      submarinerImagePullSpec: quay.io/submariner/submariner-gateway:0.13.0
      submarinerNetworkPluginSyncerImagePullSpec: quay.io/submariner/submariner-networkplugin-syncer:0.13.0
      submarinerRouteAgentImagePullSpec: quay.io/submariner/submariner-route-agent:0.13.0
```

**Submariner**
```
    imageOverrides:
      lighthouse-agent: quay.io/submariner/lighthouse-agent:0.13.0
      lighthouse-coredns: quay.io/submariner/lighthouse-coredns:0.13.0
      submariner-gateway: quay.io/submariner/submariner-gateway:0.13.0
      submariner-globalnet: quay.io/submariner/submariner-globalnet:0.13.0
      submariner-networkplugin-syncer: quay.io/submariner/submariner-networkplugin-syncer:0.13.0
      submariner-route-agent: quay.io/submariner/submariner-route-agent:0.13.0
```

**Pod Status**
```
NAME                                               READY   STATUS             RESTARTS   AGE
submariner-addon-7cc56b5c8-b78lr                   1/1     Running            0          16m
submariner-gateway-jmnwj                           0/1     ImagePullBackOff   0          7m36s
submariner-lighthouse-agent-64457966b-bl2mb        0/1     ImagePullBackOff   0          16m
submariner-lighthouse-agent-66b999f964-x8w5z       0/1     ImagePullBackOff   0          9m34s
submariner-lighthouse-coredns-845988855b-dglhm     1/1     Running            0          14m
submariner-lighthouse-coredns-845988855b-pq7pp     1/1     Running            0          14m
submariner-networkplugin-syncer-77469f76cd-2t6t6   0/1     ImagePullBackOff   0          7m33s
submariner-operator-84c556c8f8-z6j69               1/1     Running            0          11m
submariner-routeagent-4hwvf                        0/1     ImagePullBackOff   0          7m33s
submariner-routeagent-89rx9                        0/1     ImagePullBackOff   0          7m33s
submariner-routeagent-f2tmz                        0/1     ImagePullBackOff   0          7m33s
submariner-routeagent-f6rsz                        0/1     ImagePullBackOff   0          7m32s
submariner-routeagent-hr888                        0/1     ImagePullBackOff   0          7m33s
submariner-routeagent-ks2x2                        0/1     ImagePullBackOff   0          7m33s
submariner-routeagent-mcrlj                        0/1     ImagePullBackOff   0          7m32s`
```

**GatewayDaemonSet**
```
    gatewayDaemonSetStatus:
      lastResourceVersion: "353113"
      mismatchedContainerImages: false
      nonReadyContainerStates:
      - waiting:
          message: |
            rpc error: code = Unknown desc = reading manifest v0.13.0 in registry.redhat.io/rhacm2/submariner-gateway-rhel8: StatusCode: 404, Not found
          reason: ErrImagePull
```

**RouteAgentDaemonSet**
```
    routeAgentDaemonSetStatus:
      lastResourceVersion: "353292"
      mismatchedContainerImages: false
      nonReadyContainerStates:
      - waiting:
          message: |
            rpc error: code = Unknown desc = reading manifest v0.13.0 in registry.redhat.io/rhacm2/submariner-route-agent-rhel8: StatusCode: 404, Not found
          reason: ErrImagePull
```

Only lighthousecoredns deployment picked the correct version and came up with right image.

**Steps to Reproduce**

1. Install OCP 4.10 and ACM 2.6 [using deploy repo]
2. Import cluster and install submarineraddon
3. Edit `clusterserviceversion` for the managedcluster to use upstream submariner images
```
export cluster=red
export submrepo="quay.io/submariner"
export submver=0.13.0
kubectl patch submarinerconfigs submariner -n ${cluster} --type "json" -p '[
{"op":"add","path":"/spec/imagePullSpecs/submarinerImagePullSpec","value":"'${submrepo}'/submariner-gateway:'${submver}'"},
{"op":"add","path":"/spec/imagePullSpecs/submarinerRouteAgentImagePullSpec","value":"'${submrepo}'/submariner-route-agent:'${submver}'"},
{"op":"add","path":"/spec/imagePullSpecs/lighthouseAgentImagePullSpec","value":"'${submrepo}'/lighthouse-agent:'${submver}'"},
{"op":"add","path":"/spec/imagePullSpecs/lighthouseCoreDNSImagePullSpec","value":"'${submrepo}'/lighthouse-coredns:'${submver}'"},
{"op":"add","path":"/spec/imagePullSpecs/submarinerGlobalnetImagePullSpec","value":"'${submrepo}'/submariner-globalnet:'${submver}'"},
{"op":"add","path":"/spec/imagePullSpecs/submarinerNetworkPluginSyncerImagePullSpec","value":"'${submrepo}'/submariner-networkplugin-syncer:'${submver}'"}]'
```
4. check `SubmarinerConfigs` and `Submariners` for the managedcluster to make sure changes are applied.
